### ISSUE TITLE
Removing the `wp` from the URLs

### ISSUE THREAD

**Issue by fklein-lu** [stuartshields/chassis-vip#12]
I've setup a standard Chassis-VIP site, and the URLs all have `wp` in them: http://vip.local/wp/2017/02/23/hello-world

Is there a way to remove those.

**Comment by stuartshields** [comment]
Sounds like you have the sub-directory setup. Can you confirm.

**Comment by fklein-lu** [comment]
The setup is the out of the box Chassis setup with the VIP extension installed.

When I create a new site, it asks for a subdomain.

**Comment by stuartshields** [comment]
@fklein-lu Did you use the https://github.com/stuartshields/vip-config as part of the config setup?

**Comment by fklein-lu** [comment]
I destroyed my existing box, and started over today, following these steps:
```
git clone https://github.com/Chassis/Chassis.git vip-chassis
cd vip-chassis
git clone https://github.com/stuartshields/vip-config.git content
vagrant up
git clone https://github.com/stuartshields/chassis-vip.git extensions/vip
git clone https://github.com/Chassis/Tester.git extensions/tester --recursive
vagrant provision
```

When I log into WP Admin, and view the default post, this is its URL: http://vip.local/wp/2017/03/01/hello-world/

The _Add New Site_ screen asks me for a subdomain of a new site.

**Comment by stuartshields** [comment]
@fklein-lu  I'll have a look into this tonight. It could be something to do with Tester extension.

**Comment by stuartshields** [comment]
@fklein-lu This actually looks like default multisite behaviour in Chassis. 

Does it matter if the `/wp/` is added to the end of the Urls? I noticed that removing the `/wp/` also makes the URL work. If it's an issue can you lodge a ticket here: https://github.com/Chassis/Chassis/issues/ and ping Ryan to take a look?

**Comment by fklein-lu** [comment]
@stuartshields In my case it matters, because I'm using additional routing besides the WordPress one. It's not a huge deal, but still would be nicer without the `wp`.

I appreciate the follow up on this, I'll close this in favour of the issue on the Chassis repo.
