### ISSUE TITLE
Issues with the Setup Directions

### ISSUE THREAD

**Issue by mikeselander** [stuartshields/chassis-vip#6]
Hey Stuart - thanks so much for putting the time into this! Provisioned in about the quarter of the time of a VIP Quickstart instance so 🎉 

**Couple of things I noticed on the setup though:**
1. On step #2 it says to paste the config.yaml into the `vagrant` folder but on a fresh pulldown for me the config was in the top level
2. After setting the site up, I attempted to Activate Jetpack as a regular plugin but got a fatal error instead that implied that Jetpack was already being loaded. This makes sense for a VIP site, but there's no indication that Jetpack is running anywhere. All the other plugins seem to be loading fine.

I'll happily dig into the Jetpack issue as I have time, but if you've already run into this please let me know :)

Thanks again!

**Comment by stuartshields** [comment]
@mikeselander Looking into this tonight. Thanks for the report 👍

**Comment by stuartshields** [comment]
@mikeselander I've updated the Readme file, instead of copying in the config file, we'll clone it in before we provision up. I'm working on issue 2 now.

**Comment by stuartshields** [comment]
@mikeselander Just merged in fixes into master. Let me know how you go.
